# Generated by Django 2.2.11 on 2020-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shellies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shelly_id', models.CharField(max_length=100)),
                ('shelly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shelly_mac', models.CharField(blank=True, max_length=50, null=True)),
                ('shelly_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('shelly_new_fw', models.BooleanField(default=False)),
                ('shelly_fw_version', models.CharField(max_length=100)),
                ('last_change_ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shellies',
                'managed': True,
            },
        ),
    ]
