# Generated by Django 2.2.11 on 2020-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200316_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='shelly_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shellies',
            name='shelly_fw_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
