# Generated by Django 2.2.11 on 2020-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_auto_20200317_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='last_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
