# Generated by Django 2.2.11 on 2020-03-18 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_shellies_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='shelly_last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shellies',
            name='shelly_online',
            field=models.BooleanField(default=False),
        ),
    ]
