# Generated by Django 2.2.11 on 2020-03-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_auto_20200318_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='shelly_do_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shellies',
            name='shelly_last_online',
            field=models.DateTimeField(verbose_name=1),
        ),
    ]
