# Generated by Django 2.2.11 on 2020-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_auto_20200318_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHabThings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thing_uid', models.CharField(max_length=100, unique=True)),
                ('thing_label', models.CharField(max_length=200, unique=True)),
                ('thing_location', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'managed': True,
                'db_table': 'openhab_things',
            },
        ),
    ]
