# Generated by Django 2.2.11 on 2020-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_openhabthings'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhabthings',
            name='last_change_ts',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
