# Generated by Django 2.2.11 on 2020-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_openhabthings_last_change_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhabthings',
            name='thing_label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='openhabthings',
            name='thing_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
