# Generated by Django 2.2.11 on 2020-03-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0010_openhabthings_shelly_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhabthings',
            name='shelly_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelly2thing', to='updates.Shellies'),
        ),
    ]
