# Generated by Django 2.2.11 on 2020-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0011_auto_20200320_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shelly_id', models.CharField(max_length=100, unique=True)),
                ('shelly_settings_json', models.TextField(blank=True, null=True)),
                ('shelly_status_json', models.TextField(blank=True, null=True)),
                ('last_change_ts', models.DateTimeField(auto_now=True)),
                ('last_status_settings', models.CharField(blank=True, max_length=200, null=True)),
                ('last_status_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'shellies_settings',
            },
        ),
    ]
