# Generated by Django 2.2.11 on 2020-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0015_auto_20200323_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellysettings',
            name='shelly_battery_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shellysettings',
            name='shelly_battery_voltage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
