# Generated by Django 2.2.11 on 2020-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0016_auto_20200324_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='shelly_fw_version_new',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
