# Generated by Django 2.2.11 on 2020-04-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0017_shellies_shelly_fw_version_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellies',
            name='shelly_fw_version_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
