# Generated by Django 2.2.11 on 2020-04-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0018_shellies_shelly_fw_version_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataShellySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('md_settings_type', models.CharField(choices=[('GENERAL', 'General settings'), ('WIFI-AP', 'Internal Wifi AP'), ('WIFI1', 'Wifi Connection'), ('WIFI2', 'Wifi Connection Backup'), ('LOGIN', 'Credentials')], max_length=50)),
                ('md_settings_path', models.CharField(max_length=100)),
                ('md_settings_parameter', models.CharField(max_length=100)),
                ('md_settings_parameter_type', models.CharField(choices=[('bool', 'Boolean'), ('string', 'String'), ('number', 'Number')], max_length=100)),
                ('md_settings_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'masterdata_shelly_settings',
                'managed': True,
                'unique_together': {('md_settings_path', 'md_settings_parameter')},
            },
        ),
        migrations.CreateModel(
            name='MasterDataShellySettingsMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_setmatrix_shellytype', models.CharField(choices=[('SHELLY1', 'Shelly1'), ('SHELLY1PM', 'Shelly1 PM'), ('SHELLYSWITCH', 'Shelly2'), ('SHELLYSWITCH25', 'Shelly2.5'), ('SHELLY4PRO', 'Shelly 4Pro'), ('SHELLYPLUG', 'Shelly Plug'), ('SHELLYPLUG-S', 'Shelly Plug S'), ('SHELLYVINTAGE', 'Shelly Vintage'), ('SHELLYRGBW2', 'Shelly RGBW2'), ('SHELLYDIMMER', 'Shelly Dimmer'), ('SHELLYSENSE', 'Shelly Sense'), ('SHELLYHT', 'Shelly H&T'), ('SHELLYSMOKE', 'Shelly Smoke'), ('SHELLYEM', 'Shelly EM'), ('SHELLYEM3', 'Shelly 3EM'), ('SHELLYFLOOD', 'Shelly Flood')], max_length=30)),
                ('md_setmatrix_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settingsmatrix', to='updates.MasterDataShellySettings')),
            ],
            options={
                'db_table': 'masterdata_shelly_settings_matrix',
                'managed': True,
                'unique_together': {('md_setmatrix_setting', 'md_setmatrix_shellytype')},
            },
        ),
    ]
