# Generated by Django 2.2.11 on 2020-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0019_masterdatashellysettings_masterdatashellysettingsmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdatashellysettings',
            name='md_settings_single',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterdatashellysettings',
            name='md_settings_type',
            field=models.CharField(choices=[('General', 'General settings'), ('WifiAP', 'Internal Wifi AP'), ('Wifi1', 'Wifi Connection'), ('Wifi2', 'Wifi Connection Backup'), ('Login', 'Credentials')], max_length=50),
        ),
    ]
