# Generated by Django 2.2.11 on 2020-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0020_auto_20200415_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdatashellysettings',
            name='md_settings_reference_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
