# Generated by Django 2.2.11 on 2020-04-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0021_masterdatashellysettings_md_settings_reference_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellySettingUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shelly_settings_path', models.CharField(max_length=200)),
                ('shelly_settings_json', models.TextField()),
                ('shelly_settings_applied', models.BooleanField(default=False)),
                ('shelly_settings_delete', models.BooleanField(default=False)),
                ('insert_ts', models.DateTimeField(auto_now_add=True)),
                ('last_status_ts', models.DateTimeField(auto_now=True)),
                ('last_status', models.CharField(blank=True, max_length=200, null=True)),
                ('shelly_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelly2updates', to='updates.Shellies')),
            ],
            options={
                'managed': True,
                'db_table': 'shellies_settings_updates',
            },
        ),
    ]
