# Generated by Django 2.2.11 on 2020-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0022_shellysettingupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellysettingupdates',
            name='last_status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shellysettingupdates',
            name='shelly_settings_encoded',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
