# Generated by Django 2.2.11 on 2020-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0023_auto_20200416_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellysettings',
            name='shelly_wifi_ssid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shellysettings',
            name='shelly_wifi_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdatashellysettingsmatrix',
            name='md_setmatrix_shellytype',
            field=models.CharField(choices=[('SHELLY1', 'Shelly1'), ('SHELLY1PM', 'Shelly1 PM'), ('SHELLYSWITCH', 'Shelly2'), ('SHELLYSWITCH25', 'Shelly2.5'), ('SHELLY4PRO', 'Shelly 4Pro'), ('SHELLYPLUG', 'Shelly Plug'), ('SHELLYPLUG-S', 'Shelly Plug S'), ('SHELLYVINTAGE', 'Shelly Vintage'), ('SHELLYRGBW2', 'Shelly RGBW2'), ('SHELLYDIMMER', 'Shelly Dimmer'), ('SHELLYSENSE', 'Shelly Sense'), ('SHELLYHT', 'Shelly H&T'), ('SHELLYSMOKE', 'Shelly Smoke'), ('SHELLYEM', 'Shelly EM'), ('SHELLYEM3', 'Shelly 3EM'), ('SHELLYFLOOD', 'Shelly Flood'), ('SHELLYDW', 'Shelly Door/Window')], max_length=30),
        ),
    ]
