# Generated by Django 2.2.11 on 2020-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0024_auto_20200422_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatashellysettings',
            name='md_settings_type',
            field=models.CharField(choices=[('General', 'General settings'), ('WifiAP', 'Internal Wifi AP'), ('Wifi1', 'Wifi Connection'), ('Wifi2', 'Wifi Connection Backup'), ('Login', 'Credentials'), ('Device', 'Device specific')], max_length=50),
        ),
    ]
